---
  - block:

    - name: Falco | Add GPG key to apt keyring
      apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public  state=present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    - name: Falco | Add Debian apt repository
      apt_repository:
        repo: "deb http://download.draios.com/stable/deb stable-$(ARCH)/"
        state: present
        update_cache: yes
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    - name: Falco | Install kernel packages
      package:
        name: "linux-headers-{{ ansible_kernel }}"
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    - name: Falco | Install packages
      package:
        name:
          - falco
          - jq
          - mailutils
          - sysdig-dkms
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    when: ansible_os_family == "Debian"

  - block:

    - name: Falco | Yum repository
      yum_repository:
        name: Draios
        description: Falco tool
        baseurl: "http://download.draios.com/stable/rpm/$basearch"
        gpgcheck: yes
        gpgkey: "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
        enabled: yes
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    - name: Falco | Enable Import RPM key
      rpm_key:
        key: "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    - name: Falco | Install kernel packages
      package:
        name: "kernel-devel-{{ ansible_kernel }}"
        state: present
      retries: 3
      register: result
      until: result is not failed
      ignore_errors: true
      become: yes
      tags:
        - falco

    - name: Falco | Epel dependency
      package:
        name: epel-release
        state: present
      become: yes
      register: result
      until: result is succeeded
      retries: 3

    - name: Falco | Install packages
      package:
        name:
        - dkms
        - falco
        - sysdig
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - falco

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Falco | Template root config
    template:
      src: "{{ falco_root_config_template }}"
      dest: "/etc/falco/falco.yaml"
    become: yes
    tags:
      - falco

  - name: Falco | Enable service
    service:
      name: falco
      state: started
      enabled: yes
    retries: 3
    register: result
    until: result is not failed
    when: docker_test is not defined
    become: yes
    tags:
      - falco
